@extends('layouts.layout')
@section('content')
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">

        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Purchase Order List
                </div>

                <div class="col-md-8 text-right">
                    <div class="d-block">
                        @can('add medicine purchase order')
                        <a href="{{route('add-medicine-purchase-order')}}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Create Purchase Order</a>
                        @endcan
                    </div>
                </div>

            </div>
        </div>

        @include('message.notification')
        @can('View Medicine Purchase Order')

        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table id="example" class="table table-borderless text-nowrap key-buttons">
                        <thead>
                            <tr>
                                <th scope="col">Sl No.</th>
                                <th scope="col">Purchase Order No.</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Store Room</th>
                                <th scope="col">Date</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(isset($po_list) && $po_list != '')
                            @foreach ($po_list as $po)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td><a href="{{route('purchase-order-details')}}/{{base64_encode($po->id)}}" style="color: blue;">{{$po->po_prefix}}{{ @$po->id }}</a></td>
                                <td>{{$po->get_user_details->first_name}} {{$po->get_user_details->last_name}}</td>
                                <td>{{@$po->get_store_details->name}}</td>
                                <td><?= date('d-m-Y h:i', strtotime($po->po_date)); ?></td>
                                <td>{!!@$po->get_wroking_status_details->status!!}</td>
                                <td>
                                    <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" style="">
                                            @can('Print Medicine Purchase Order')
                                            <a class="dropdown-item" href="{{ route('po-print',['po_id'=> base64_encode($po->id)]) }}"><i class="fa fa-print"></i> Print</a>
                                            @endcan
                                            <a class="dropdown-item" href="{{route('purchase-order-details')}}/{{base64_encode($po->id)}}"><i class="fa fa-eye"></i> View</a>
                                            {{-- @can('Edit medicine purchase order')
                                            @if($po->po_status<=11 || $po->po_status==17)
                                                <a class="dropdown-item" href=""><i class="fa fa-edit"></i> Edit</a>
                                                @endif
                                                @endcan --}}
                                            @can('delete medicine purchase order')
                                            <a class="dropdown-item" href="{{ route('po-delete',['id'=>base64_encode($po->id)]) }}"><i class="fa fa-trash"></i> Delete</a>
                                            @endcan
                                        </div>
                                    </div>
                                </td>


                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->
                </div>
            </div>
        </div>
        @endcan
    </div>
</div>

<script src="{{ asset('assets/js/jquery-3.6.0.min.js') }}"></script>
<script>
    $(document).ready(function() {
        $("#removeIcon").click(function(e) {
            e.preventDefault();
            $("#delete").submit();
        });
    });
</script>
@endsection