@extends('layouts.layout')
@section('content')

@php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
@endphp



<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header">
            <div class="card-new">
            <div class="card-title">
                Purchase Order Details
                @can('Print Medicine Purchase Order')
                <a href="{{ route('po-print',['po_id'=> base64_encode($po_list->id)]) }}" class="btn btn-primary btn-sm allbtndemo"><i class="fa fa-print"> Print</i></a>
                @endcan
        
                @can('permission on po section')
                <a href="#" class="btn btn-primary btn-sm allbtndemoffff" data-target="#modaldemo1241" data-toggle="modal"><i class="fa fa-user"> Permission</i></a>
                @endcan
            </div>
            </div>
        </div>
        @include('message.notification')
        @can('view medicine requisition')
        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="requisition_header">Store Room : </span><span class="requisition_text">{{ @$po_list->get_store_details->name }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Purchase Order No. : </span><span class="requisition_text">{{$po_list->po_prefix}}{{ @$po_list->id }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Purchase Order Date : </span><span class="requisition_text"><?= date('d-m-Y h:i', strtotime($po_list->po_date)); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Generated By : </span><span class="requisition_text">{{@$po_list->get_user_details->first_name}}{{@$po_list->get_user_details->last_name}}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Vendor : </span><span class="requisition_text">{{@$po_list->get_vendor_details->vendor_name}}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Note : </span><span class="requisition_text">{{@$po_list->note}}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_text">{!!@$po_list->get_wroking_status_details->status!!}</span>
                            </div>
                        </div>

                        <div style="padding: 26px 0px 0px 0px;">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        @can('save feedback')
                                        @if($po_list->status == 13 || $po_list->status == 19)
                                        <a class="btn btn-primary btn-sm" data-target="#modaldemo3" data-toggle="modal" href="#"><i class="fa fa-envelope"></i> Upload Feedback</a>
                                        @endif
                                        @endcan
                                        @if(!empty($po_list->feedback))
                                        <a href="{{ asset('feedback/') }}/{{$po_list->feedback}}" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b> View Feedback</b></i></a>
                                        @endif
                                    </div>

                                    @if(!empty($po_list->feedback))
                                    <div class="col-md-6">
                                        <span data-toggle="tooltip-primary" data-placement="top" title="Upload Expected Delivary Date">
                                            @if($po_list->status > 11 && $po_list->status < 15 || $po_list->status == 19)
                                                <a class="btn btn-primary btn-sm" data-target="#modaldemo12" data-toggle="modal" href="#"><i class="fa fa-calendar"></i></a></span>
                                        @endif
                                        @if(!empty($po_list->expected_delivery_date))
                                        <span class="requisition_header">Expected Delivary Date : </span><span class="requisition_text"><?= date('d-m-Y', strtotime($po_list->expected_delivery_date)); ?></span>
                                        @endif

                                    </div>
                                    @endif

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Requisition Id</th>
                            <th>Medicine Name</th>
                            <th>Medicine Unit</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($po_item) && $po_item != '')
                        @foreach($po_item as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{@$item->req_id}}</td>
                            <td>{{@$item->fetch_medicine_name->medicine_name}}({{@$item->fetch_medicine_name->catagory_name->medicine_catagory_name}})</td>
                            <td>{{@$item->fetch_medicine_unit->medicine_unit_name}}</td>
                            <td>{{@$item->quantity}}</td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>


            </div><!-- bd -->
        </div>
        @endcan
    </div>
</div>

<div class="modal" id="modaldemo3">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Upload Feedback</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="{{route('feedback-save')}}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="po_id" value="{{$po_list->id}}">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Feedback <span class="text-danger">*</span></label>
                        <input type="file" value="{{@$po_list->feedback}}" required name="feedback_file">
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="modaldemo12">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Expected Delivery Date</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="{{route('expected-delivery-date')}}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="po_id" value="{{$po_list->id}}">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Expected Delivery Date <span class="text-danger">*</span></label>
                        <input type="date" value="{{@$po_list->expected_delivery_date}}" required name="expected_delivery_date" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="modaldemo1241">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Purchase Order</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="{{route('po-status-change')}}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="po_id" value="{{$po_list->id}}">
                <input type="hidden" name="vendor_id" value="{{$po_list->get_vendor_details->id}}">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Status <span class="text-danger">*</span></label>
                        <select class="form-control" name="status">
                            <option vlue="" disabled>Select One</option>
                            {{-- <option value="16" <?php if ($po_list->status == 16) {
                                                    echo "selected";
                                                } ?>>Purchase Order Holded</option>
                            <option value="15" <?php if ($po_list->status == 15) {
                                                    echo "selected";
                                                } ?>>Purchase Order Cancelled</option> --}}
                            <option value="17" <?php if ($po_list->status == 17) {
                                                    echo "selected";
                                                } ?>>Purchase Order Confirmed</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- ================================ vendor quatation details========================= -->
{{-- <div class="modal" id="modaldemo3fgfg">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Add Vendor/Quatation</h6>

                <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

                <div class="table-responsive">
                    <table class="table table-striped card-table table-vcenter text-nowrap">
                        <thead>
                            <tr>
                                <th>Vendor Details</th>
                                <th>Quatation</th>
                                <th>Select Quatation</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if(isset($sl_vender))
                            @foreach($sl_vender as $value)
                            <tr>
                                <td>{{$value->sl_vendors_join->vendor_name}}
                                    <br>
                                    @if($value->status == 1)
                                    <a class="btn btn-pill btn-secondary btn-sm" href="#" type="button">Selected</a>
                                    @endif
                                    @if($value->status == 2)
                                    <a class="btn btn-pill btn-warning btn-sm" href="#" type="button">Hold</a>
                                    @endif
                                </td>
                                <td>
                                    @if($value->vendor_quatation != null)
                                    <a style="color:blue" href="{{ asset('public/quatation/') }}/{{@$value->vendor_quatation}}" target="_blank"><i class="fa fa-eye"></i> View Quatation</a>
                                    @endif
                                </td>
                                <td>
                                    <form method="POST" action="{{route('vendor-select-change-afetr-po')}}">
                                        @csrf
                                        <textarea name="note" class="form-control">{{@$value->comment}}</textarea>
                                        <input type="hidden" name="po_id" value="{{@$po_list->id}}">
                                        <br>
                                        <select name="selection" class="form-control" required>
                                            <option value="">Select One</option>
                                            <option value="1" <?php if ($value->status == 1) {
                                                                    echo "Selected";
                                                                } ?>>Selected</option>
                                            <option value="2" <?php if ($value->status == 2) {
                                                                    echo "Selected";
                                                                } ?>>Hold</option>
                                        </select>
                                        <br>
                                        <!--       <select name="item_quataion" required class="select2-show-search" class="form-control">
                                            <option value="0" selected>All Item</option>
                                            @if(isset($requisition_item) && $requisition_item != '')
                                            @foreach($requisition_item as $requisition)
                                            <option value="{{$requisition->requisition_details_id}}">{{@$requisition->item_name}}<br>({{@$requisition->item_description}})</option>
                                            @endforeach
                                            @endif
                                        </select> -->

                                        <input type="hidden" name="vendor_id" value="{{$value->sl_vendors_join->id}}">
                                        <input type="hidden" name="req_no" value="{{$value->req_id}}">
                                        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Select</button>
                                        <br>
                                    </form>
                                </td>

                            </tr>
                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div> --}}
<!-- ================================ vendor quatation details========================= -->

<!--  -->








@endsection