@extends('layouts.layout')
@section('content')


@php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
@endphp



<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                GRN Details
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="requisition_header">Store Room : </span><span class="requisition_text">{{ @$grn_list->store_room_details->name }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN No. : </span><span class="requisition_text">{{ @$grn_list->grn_prefix }}{{ @$grn_list->id }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN Date : </span><span class="requisition_text"><?= date('d-m-Y h:i', strtotime(@$grn_list->grn_date)) ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Generated By : </span><span class="requisition_text">{{ @$grn_list->fetch_user_details->first_name }}{{ @$grn_list->fetch_user_details->last_name }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Medicine Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grn_list->medicine_rec_date)); ?></span>
                            </div>
                            @if (@isset($grn_list->bill_rec_date))
                            <div class="col-md-6">
                                <span class="requisition_header">Bill Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grn_list->bill_rec_date)); ?></span>
                            </div>
                            @endif

                            <div class="col-md-6">
                                <span class="requisition_header">Challan No. : </span><span class="requisition_text"><?php echo @$grn_list->challan_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Challan Date : </span><span class="requisition_text">{{@$grn_list->challan_date}}
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Date : </span><span class="requisition_text">{{@$grn_list->invoice_date}}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice No : </span><span class="requisition_text"><?php echo @$grn_list->invoice_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Value : </span><span class="requisition_text"><?php echo @$grn_list->invoice_value; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">PO. No. : </span><span class="requisition_text"><a target="_blank" href="{{route('purchase-order-details')}}/{{base64_encode($po_details->id)}}" style="color: blue;">{{$po_details->po_prefix}}{{$po_details->id}}</a>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total CGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_cgst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total SGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_sgst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total IGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_igst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_value; ?></span>
                                </span>
                            </div>
                    
                            @isset($grn_list->note)
                            <div class="col-md-12">
                                <span class="requisition_header">Note : </span><span class="requisition_text">{{ @$grn_list->note }}</span>
                            </div>
                            @endisset
                
                        </div>

                    </div>

                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>SL No.</th>
                            <th>Req. No.</th>
                            <th>Medicine Name</th>
                            <th>Catagory</th>
                            <th>Batch No.</th>
                            <th>Unit</th>
                            <th>Quantity</th>
                            <th>Discount</th>
                            <th>MRP</th>
                            <th>Purchase Rate</th>
                            <th>Sale Rate</th>
                            <th>CGST</th>
                            <th>CGST Value</th>
                            <th>SGST</th>
                            <th>SGST Value</th>
                            <th>IGST</th>
                            <th>IGST Value</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (isset($grn_item) && $grn_item != '')
                        @foreach ($grn_item as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ @$item->req_id }}</td>
                            <td>{{ @$item->fetch_medicine_name->medicine_name }}</td>
                            <td>{{ @$item->fetch_medicine_catagory->medicine_catagory_name }}</td>
                            <td>{{ @$item->batch_no }}</td>
                            <td>{{ @$item->fetch_medicine_unit->medicine_unit_name }}</td>
                            <td>{{ @$item->qty }}</td>
                            <td>{{ @$item->discount }}</td>
                            <td>{{ @$item->mrp }}</td>
                            <td>{{ @$item->p_rate }}</td>
                            <td>{{ @$item->s_rate }}</td>
                            <td>{{ @$item->cgst }}</td>
                            <td>{{ @$item->cgst_value }}</td>
                            <td>{{ @$item->sgst }}</td>
                            <td>{{ @$item->sgst_value }}</td>
                            <td>{{ @$item->igst }}</td>
                            <td>{{ @$item->igst_value }}</td>
                            <td>{{ @$item->amount }}</td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>

            </div><!-- bd -->
        </div>
    </div>
</div>











@endsection