
<?php $__env->startSection('content'); ?>


<?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('view vender in requisition section')): ?>
<?php if($requisition_details->status == 5): ?>
<div class="card">
<div class="card-body">
    <div class="col-md-12">
        <form method="POST" action="<?php echo e(route('add-vender-for-quatation')); ?>">
            <?php echo csrf_field(); ?>
            <input type="hidden" name="req_id" value="<?php echo e($requisition_details->req_no); ?>">
        <div class="row">
            <div class="col-md-8">
                <?php if(isset($vendor_details)): ?>
                  <select name="vendor_name[]" multiple="multiple" class="multi-select select2-show-search">
                      <option>Select Vendor</option>
                      <?php $__currentLoopData = $vendor_details; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                         <option value="<?php echo e($value->id); ?>"><?php echo e($value->vendor_name); ?>,<?php echo e($value->vendor_address); ?>,<?php echo e($value->vendor_gst); ?></option>
                      <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                  </select>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary" type="submit"><i class="fa fa-envelope"></i> Send For RFQ</button>
            </div>
        </div>
      </form>

    </div>
</div>
</div>
<?php endif; ?>
<?php endif; ?>

<?php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
?>

<div class="col-md-12">
<div class="row">
<div class="col-lg-8 col-xl-8 col-md-8 col-sm-8">
    <div class="card">
            <div class="card-header">
                <div class="card-title">Requisition Details</div>
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('Add Vendor Quatation')): ?>
                <a class="btn btn-primary" style="position: absolute; margin-left: 553px;" data-target="#modaldemoadd_rfq" data-toggle="modal" href=""><i class="fa fa-plus"></i> Add Vendor Quatation</a>
                <?php endif; ?>
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('Vendor Quatation List')): ?>
                <a class="btn btn-primary" style="position: absolute; margin-left: 341px;" data-target="#modaldemoadd_rfq_list" data-toggle="modal" href=""><i class="fa fa-list"></i> Vendor Quatation List</a>
                <?php endif; ?>
            </div>
        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('view requisition details')): ?>
        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition No : </span><span class="requisition_text"><?php echo e($prefix->prefix); ?><?php echo e(@$requisition_details->req_no); ?></span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition Date : </span><span class="requisition_text"><?= date('d-m-Y h:i',strtotime($requisition_details->date)); ?></span>
                    </div>
                     <div class="col-md-4">
                        <span class="requisition_text">
                            <?php echo @$requisition_details->req_status; ?>

                       </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Generated By : </span><span class="requisition_text"><?php echo e(@$requisition_details->issue_by_name); ?></span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Requested By : </span><span class="requisition_text"><?php echo e(@$requisition_requested_by->name); ?></span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Note : </span><span class="requisition_text"><?php echo e(@$requisition_details->notes); ?></span>
                    </div>
                    <hr>
                    <?php if(!empty($vendor_selected_quataion)): ?>
                    <?php $__currentLoopData = $vendor_selected_quataion; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <div class="col-md-4">
                        <span class="requisition_header">Selected Vendor Details : </span><br><span class="requisition_text"><?php echo e($value->vendor_name); ?>,<?php echo e($value->vendor_address); ?>,<?php echo e($value->vendor_gst); ?></span>
                    </div>
                     <div class="col-md-8">
                        <span class="requisition_header">Selected Vendor Quatation : </span><br><span class="requisition_text"><a href="<?php echo e(asset('public/quatation/')); ?>/<?php echo e(@$value->vendor_quatation); ?>" target="_blank"><img src="<?php echo e(asset('public/quatation/')); ?>/<?php echo e(@$value->vendor_quatation); ?>" height="75px" width="75px" /></a></span>
                    </div>
                    
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    <?php endif; ?>

                    <?php if($requisition_details->status == 9): ?>
                    <div class="col-md-12">
                       <span class="requisition_header"> <a class="btn btn-primary " style="    margin-top: 17px;margin-left: 467px;" data-target="#modaldemoadd_rfq_vendor" data-toggle="modal" href=""><i class="fa fa-user"></i> Permission For Selected Vendor</a></span>
                    </div>
                    <?php endif; ?>
                    
                </div>
                
            </div> 
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Item Name</th>
                            <th>Item Barcode</th>
                            <th>Brand</th>
                            <th>Manufacturer</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(isset($requisition_item) && $requisition_item != ''): ?>
                        <?php $__currentLoopData = $requisition_item; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $requisition): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <th scope="row"><?php echo e($loop->iteration); ?></th>
                                <td><?php echo e(@$requisition->item_name); ?><br>(<?php echo e(@$requisition->item_description); ?>)</td>
                                 <td><img src="data:image/png;base64,<?php echo e(base64_encode($generatorPNG->getBarcode($requisition->product_code, $generatorPNG::TYPE_CODE_128))); ?>">
                                    <br><span style="margin-left: 20px"><?php echo e(@$requisition->product_code); ?></span>
                                </td>
                                <td><?php echo e(@$requisition->brand_name); ?></td>
                                <td><?php echo e(@$requisition->manufacturar_name); ?></td>
                                <td><?php echo e(@$requisition->quantity); ?> <?php echo e(@$requisition->units); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                        <?php endif; ?>
       
                    </tbody>
                </table>
            </div><!-- bd -->
        </div>
        <?php endif; ?>
    </div>
</div>

<div class="col-lg-4 col-xl-4 col-md-4 col-sm-4">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Requisition Permission Activity</h3>
        <div class="card-options">
        <?php if(isset($permisison_users) && $permisison_users != ''): ?>
        <?php $__currentLoopData = $permisison_users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <?php if($user->user_id == Auth::id() && $user->status != 'Approved'): ?>
             <a class="btn btn-primary" data-target="#modaldemo1" data-toggle="modal" href="">Permission</a>
        <?php endif; ?>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        <?php endif; ?>    
        </div>
        </div>
        <div class="card-body">
            <div class="latest-timeline scrollbar3" id="scrollbar3">
                <ul class="timeline mb-0">
                <?php if(isset($permisison_users) && $permisison_users != ''): ?>
                    <?php $__currentLoopData = $permisison_users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>

                    <li class="mt-0">
                        <div class="d-flex"><span class="time-data"><?php echo e(@$user->name); ?></span><span class="ml-auto text-muted fs-11"><?php if($user->date != '' && $user->date != null){ echo date('d-m-Y h:i',strtotime($user->date)); } ?></span></div>
                        <p class="text-muted fs-12"><span class="text-info">

                           <?php if($user->status == 'Pending')
                           {
                                echo '<td><button class="btn btn-pill btn-warning btn-sm" type="button">Pending</button></td>';
                           }
                           if($user->status == 'Approved')
                           {
                                echo '<td><button class="btn btn-pill btn-success btn-sm" type="button">Approved</button></td>';
                           }
                           if($user->status == 'Rejected')
                           {
                                echo '<td><button class="btn btn-pill btn-success btn-sm" type="button">Rejected</button></td>';
                           }
                            ?>
                            


                        </span> </p>
                        <p class="text-muted fs-12"><span class="text-info"><?php echo e(@$user->comment); ?></span> </p>
                    </li>

                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php endif; ?>    
                </ul>
            </div>
        </div>
    </div>
    <?php if(count($permisison_users_vendor) > 0): ?>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Selected Vendor Permission Activity</h3>
        <div class="card-options">
        <?php if(isset($permisison_users_vendor) && $permisison_users_vendor != ''): ?>
        <?php $__currentLoopData = $permisison_users_vendor; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <?php if($user->user_id == Auth::id() && $user->status != 'Approved'): ?>
             <a class="btn btn-primary" data-target="#modaldemo11" data-toggle="modal" href="">Permission</a>
        <?php endif; ?>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        <?php endif; ?>    
        </div>
        </div>
        <div class="card-body">
            <div class="latest-timeline scrollbar3" id="scrollbar3">
                <ul class="timeline mb-0">
                <?php if(isset($permisison_users_vendor) && $permisison_users_vendor != ''): ?>
                    <?php $__currentLoopData = $permisison_users_vendor; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>

                    <li class="mt-0">
                        <div class="d-flex"><span class="time-data"><?php echo e(@$user->name); ?></span><span class="ml-auto text-muted fs-11"><?php if($user->date != '' && $user->date != null){ echo date('d-m-Y h:i',strtotime($user->date)); } ?></span></div>
                        <p class="text-muted fs-12"><span class="text-info">

                           <?php if($user->status == 'Pending')
                           {
                                echo '<td><button class="btn btn-pill btn-warning btn-sm" type="button">Pending</button></td>';
                           }
                           if($user->status == 'Approved')
                           {
                                echo '<td><button class="btn btn-pill btn-success btn-sm" type="button">Approved</button></td>';
                           }
                           if($user->status == 'Rejected')
                           {
                                echo '<td><button class="btn btn-pill btn-success btn-sm" type="button">Rejected</button></td>';
                           }
                            ?>
                            


                        </span> </p>
                      
                    </li>

                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php endif; ?>    
                </ul>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>


</div>
</div>

<div class="modal" id="modaldemo1">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Given Permission</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('given-approval')); ?>">
                <?php echo csrf_field(); ?>
            <div class="modal-body">
            <div class="col-md-12">
            <div class="row">
            <div class="col-md-6">
            <label  class="form-label">
               Approve </label> <input type="radio" name="permission" value="Approved">
           </div>
           <input type="hidden" name="requisition_id" value="<?php echo e($requisition_details->req_no); ?>">
            <div class="col-md-6">
            <label  class="form-label"> Reject </label> <input type="radio" name="permission" value="Rejected"  ></div>
            </div>
            <?php $__errorArgs = ['permission'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                <span class="text-danger"><?php echo e($message); ?></span>
            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>  
            </div>
            <div class="col-md-12">
                Comment:
                <textarea name="comment" class="form-control"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-indigo" type="submit">Save</button>
            </div>
            </form>
        </div>
    </div>
</div>



<div class="modal" id="modaldemo11">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Give Permission</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('give-approval-vendor')); ?>">
                <?php echo csrf_field(); ?>
            <div class="modal-body">
            <div class="col-md-12">
            <div class="row">
            <div class="col-md-6">
            <label  class="form-label">
               Approve </label> <input type="radio" name="permission" value="Approved">
           </div>
           <input type="hidden" name="requisition_id" value="<?php echo e($requisition_details->req_no); ?>">
            <div class="col-md-6">
            <label  class="form-label"> Reject </label> <input type="radio" name="permission" value="Rejected"  ></div>
            </div>
            <?php $__errorArgs = ['permission'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                <span class="text-danger"><?php echo e($message); ?></span>
            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>  
            </div>
         
            </div>
            <div class="modal-footer">
                <button class="btn btn-indigo" type="submit">Save</button>
            </div>
            </form>
        </div>
    </div>
</div>


<div class="modal" id="modaldemoadd_rfq_list">
    <div class="modal-dialog dhrhreyre" role="document" >
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Quatation List</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
           
            <div class="modal-body">
                        <div class="table-responsive">
                    <table class="table table-striped card-table table-vcenter text-nowrap">
                        <thead>
                            <tr>
                                <th>Vendor Details</th>
                                <th>Quatation</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                             <?php if(isset($sl_vender)): ?>
                              <?php $__currentLoopData = $sl_vender; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e($value->vendor_name); ?>,<?php echo e($value->vendor_address); ?>,<?php echo e($value->vendor_gst); ?>

                                    <?php if($value['quatation_status'] == 1): ?>
                                       <button class="btn btn-pill btn-secondary btn-sm" type="button">Selected</button>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if($value->vendor_quatation != null): ?>
                                    <img src="<?php echo e(asset('public/quatation/')); ?>/<?php echo e(@$value->vendor_quatation); ?>" height="50px" width="50px" />
                                    <?php endif; ?>

                                </td>
                                <td>
            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('vendor selected for P.O')): ?>
            <?php if($value['quatation_status'] != 1): ?>
                <a href="<?php echo e(url('/vendor-select-for-po')); ?>/<?php echo e($value->vendor_id); ?>/<?php echo e($requisition_details->req_no); ?>"
                class="btn btn-success btn-sm" data-toggle="tooltip-primary" data-placement="top"
                title="Selected Quatation"><i
                class="fa fa-check"></i> Select</a>
             <?php endif; ?>
            <?php endif; ?>
            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('Vendor Quatation Edit')): ?>
                <a href="<?php echo e(url('/item-edit')); ?>"
                class="btn btn-danger btn-sm" data-toggle="tooltip-primary" data-placement="top"
                title="Edit"><i
                class="fa fa-pencil"></i> Edit</a>
            <?php endif; ?>

            </td>
                            </tr>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                             <?php endif; ?>
                           
                        </tbody>
                    </table>
                </div><!-- bd -->
            </div>
          
            
        </div>
    </div>
</div>

<div class="modal" id="modaldemoadd_rfq_vendor">
    <div class="modal-dialog" role="document" >
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Vendor Quatation Approval</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
           
            <div class="modal-body">
            <form method="POST" action="<?php echo e(route('add-vendor-permission')); ?>">  
            <?php echo csrf_field(); ?>                
            <div class="col-md-12">
                <label  class="form-label">Permission Authority</label>
               <select name="permission_authority[]" multiple="multiple" class="multi-select select2-show-search">
                   <option value="">......................... Select One ............................</option>
                   <?php if($user_list): ?>
                     <?php $__currentLoopData = $user_list; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                     <option value="<?php echo e($value->id); ?>"><?php echo e($value->name); ?></option>
                     <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                   <?php endif; ?>
               </select>
            </div>
            <input type="hidden" name="req_id" value="<?php echo e(@$requisition_details->req_no); ?>">
            <br>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            </div>
          </form> 
            
        </div>
    </div>
</div>

<div class="modal" id="modaldemoadd_rfq">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Add Vendor Quatation</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('add-vendor-quatation')); ?>" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
            <div class="modal-body">
                <input type="hidden" name="req_id" value="<?php echo e($requisition_details->req_no); ?>">
            <div class="col-md-12">
               <b> Vendor Name :</b>
              <?php if(isset($sl_vender)): ?>
                  <select class="form-control" name="vender_name"  class="select2-show-search">
                      <option>Select Vendor</option>
                      <?php $__currentLoopData = $sl_vender; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                         <option value="<?php echo e($value->vendor_id); ?>"><?php echo e($value->vendor_name); ?>,<?php echo e($value->vendor_address); ?>,<?php echo e($value->vendor_gst); ?></option>
                      <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                  </select>
                <?php endif; ?>
            
            <?php $__errorArgs = ['permissionss'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                <span class="text-danger"><?php echo e($message); ?></span>
            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>  
            </div>
            <br>
            <div class="col-md-12">
               <b> Vendor Quatation :</b>
            <input type="file" name="vendor_quatation">
            
            <?php $__errorArgs = ['permissionssss'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                <span class="text-danger"><?php echo e($message); ?></span>
            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>  
            </div>
            <br>
        
            <div class="modal-footer">
                <button class="btn btn-indigo" type="submit">Save</button>
            </div>
            </form>
        </div>
    </div>
</div>




<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH E:\xampp\ame_inventory\resources\views/appPages/item/requisition/requisition-details.blade.php ENDPATH**/ ?>