
<?php $__env->startSection('content'); ?>


<?php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
?>


<div class="col-md-12">
    <div class="row">
    <div class="col-lg-8 col-xl-8 col-md-8 col-sm-8">
        <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        EMG Challan Details
                    </div>  
                </div>
         
            <div class="card-body"> 
                <div class="col-md-12">
                    <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6">
                            <span class="requisition_header">Workshop : </span><span class="requisition_text"><?php echo e(@$emg_list->workshop_name); ?></span>
                        </div>
                        <div class="col-md-6">
                            <span class="requisition_header">EMG No. : </span><span class="requisition_text"><?php echo e(@$emg_list->emg_prefix); ?><?php echo e(@$emg_list->emg_id); ?></span>
                        </div>
                        <div class="col-md-6">
                            <span class="requisition_header">EMG Date : </span><span class="requisition_text"><?= date('d-m-Y h:i',strtotime(@$emg_list->emg_date)); ?></span>
                        </div>
                        <div class="col-md-6">
                            <span class="requisition_header">Generated By : </span><span class="requisition_text"><?php echo e(@$emg_list->name); ?></span>
                        </div>
                        <div class="col-md-6">
                            <span class="requisition_header">Materials Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i',strtotime(@$emg_list->material_rec_date)) ?></span>
                        </div>
                        <?php if($emg_list->bill_rec_date): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Bill Rec. Date : </span><span class="requisition_text"> <?php echo date('d-m-Y h:i',strtotime(@$emg_list->bill_rec_date)) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->challan_no): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Challan No. : </span><span class="requisition_text"><?php echo $emg_list->challan_no; ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->challan_date): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Challan Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i',strtotime(@$emg_list->challan_date)) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->invoice_date): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Invoice Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i',strtotime(@$emg_list->invoice_date)) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->invoice_no): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Invoice No : </span><span class="requisition_text"><?php echo @$emg_list->invoice_no; ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->invoice_value): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">Invoice Value : </span><span class="requisition_text"><?php echo @$emg_list->invoice_value; ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->po_value): ?>
                        <div class="col-md-6">
                            <span class="requisition_header">PO. Value : </span><span class="requisition_text"><?php echo @$emg_list->po_value; ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->note): ?>
                        <div class="col-md-12">
                            <span class="requisition_header">Note : </span><span class="requisition_text"><?php echo e(@$emg_list->note); ?></span>
                        </div> 
                        <?php endif; ?>
                        <?php if($emg_list->challan_copy): ?> 
                        <div class="col-md-6">
                            <a href="<?php echo e(asset('Challan_copy/')); ?>/<?php echo e(@$emg_list->challan_copy); ?>" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b> View Challan</b></i></a>
                        </div>
                        <?php endif; ?>
                        <?php if($emg_list->invoice_copy): ?> 
                        <div class="col-md-6">
                            <a href="<?php echo e(asset('invoice_copy/')); ?>/<?php echo e(@$emg_list->invoice_copy); ?>" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b> View Invoice</b></i></a>
                        </div> 
                        <?php endif; ?>
                    </div>

                   
                </div>
                <?php $qr_details = 'EMG No. - '.@$emg_list->emg_prefix.''.@$emg_list->emg_id .' , EMG Date - '.date('d-m-Y h:i',strtotime(@$emg_list->EMG_date)).' , Generated By - '.@$emg_list->name ; ?>
                <div class="col-md-4">
                    <div class="col-md-6">
                             <?php echo QrCode::size(100)->generate($qr_details); ?>

                    </div>
                </div>
                </div> 
                </div>
                <hr>
                <div class="table-responsive">
                    <table class="table table-striped card-table table-vcenter text-nowrap">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Item Name</th>
                                <th>Brand</th>
                                <th>Manufacturer</th>
                                <th>Quantity</th>
                                <th>GST</th>
                                <th>Rate</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(isset($emg_item) && $emg_item != ''): ?>
                            <?php $__currentLoopData = $emg_item; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <th scope="row"><?php echo e($loop->iteration); ?></th>
                                <td><?php echo e(@$item->item_name); ?><br>(<?php echo e(@$item->item_description); ?>)</td>
                                <td><?php echo e(@$item->brand_name); ?></td>
                                <td><?php echo e(@$item->manufacturar_name); ?></td>
                                <td><?php echo e(@$item->quantity); ?> <?php echo e(@$item->units); ?></td>
                                <td><?php echo e(@$item->gst); ?></td>
                                <td><?php echo e(@$item->rate); ?></td>
                                <td><?php echo e(@$item->amount); ?></td>
                            </tr>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <hr>
   
                </div><!-- bd -->
            </div>
        </div>
    </div>

    <!-- ============================Requisition Permission Activity================== -->
<div class="col-lg-4 col-xl-4 col-md-4 col-sm-4">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Requisition Permission Activity</h3>
            <div class="card-options">
            </div>
        </div>
        <div class="card-body">
            <div class="latest-timeline scrollbar3" id="scrollbar3">
                <ul class="timeline mb-0">
                    <?php if(isset($permisison_users) && $permisison_users != ''): ?>
                    <?php $__currentLoopData = $permisison_users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <li class="mt-0">
                        <div class="d-flex"><span class="time-data"><?php echo e(@$user->name); ?></span><span class="ml-auto text-muted fs-11"><?php if($user->date != '' && $user->date != null){ echo date('d-m-Y h:i',strtotime($user->date)); } ?></span></div>
                        <p class="text-muted fs-12">
                            <span class="text-info">
                                <?php if($user->user_id == Auth::id() && ( $user->permission_type_user_all == 'Parallal' || @$show_for_permission->user_id == Auth::id()) ): ?>
                        <td><a class="btn btn-pill btn-info btn-sm" data-target="#modaldemo1"  data-toggle="modal" type="button"><?php echo e($user->status); ?></a></td>
                        <?php else: ?>
                        <td><a class="btn btn-pill btn-info btn-sm" type="button"><?php echo e($user->status); ?></a></td>
                        <?php endif; ?>
                        </span> </p>
                        <?php if(!empty($user->comment)): ?>
                        <p class="text-muted fs-12"><span style="color:blue;cursor: pointer;" data-placement="top" data-toggle="tooltip" title="<?php echo e($user->comment); ?>" ><i class="fa fa-eye"></i> View Note</span></p>
                        <?php endif; ?>
                    </li>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    <?php endif; ?>    
                </ul>
            </div>
        </div>
    </div>
</div>
        <!-- ================Requisition Permission Activity======================== -->

    </div>
    </div>

<div class="modal" id="modaldemo1">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Change Status</h6>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('given-approval-for-emg')); ?>">
                <?php echo csrf_field(); ?>
                <div class="modal-body">
                    <div class="col-md-12">
                        <select name="permission" <?php if(@$permisison_status_own->status=='Approved'){ echo"disabled";} ?>  class="form-control" required>

                            <option value="" disabled>Select One</option>

                            <option value="Pending" disabled <?php if(@$permisison_status_own->status=='Pending'){ echo"selected";} ?> >Pending</option>

                            <option  value="Approved" <?php if(@$permisison_status_own->status=='Approved'){ echo"selected";} ?>>Approved</option>

                            <option value="Need Clarification" <?php if(@$permisison_status_own->status=='Need Clarification'){ echo"selected";} ?>>Need Clarification</option>

                            <option value="Rejected" <?php if(@$permisison_status_own->status=='Rejected'){ echo"selected";} ?>>Rejected</option>
                        </select>
                        <input type="hidden" name="emg_id" value="<?php echo e(@$emg_list->emg_id); ?>">
                    </div>
                    <div class="col-md-12">
                        Comment:
                        <textarea <?php if(@$permisison_status_own->status=='Approved'){ echo"readonly";} ?>  name="comment" class="form-control"><?php echo e(@$permisison_status_own->comment); ?></textarea>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-indigo" <?php if(@$permisison_status_own->status=='Approved'){ echo"disabled";} ?>  type="submit"><i class="fa fa-file"></i> Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>








    
 

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH E:\xampp\htdocs\ameInventory\resources\views/appPages/item/emg_challan/emg_challan_details.blade.php ENDPATH**/ ?>