
<?php $__env->startSection('content'); ?>


<?php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
?>



<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                GRN Details
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="requisition_header">Store Room : </span><span class="requisition_text"><?php echo e(@$grn_list->store_room_details->name); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN No. : </span><span class="requisition_text"><?php echo e(@$grn_list->grn_prefix); ?><?php echo e(@$grn_list->id); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN Date : </span><span class="requisition_text"><?= date('d-m-Y h:i', strtotime(@$grn_list->grn_date)) ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Generated By : </span><span class="requisition_text"><?php echo e(@$grn_list->fetch_user_details->first_name); ?><?php echo e(@$grn_list->fetch_user_details->last_name); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Medicine Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grn_list->medicine_rec_date)); ?></span>
                            </div>
                            <?php if(@isset($grn_list->bill_rec_date)): ?>
                            <div class="col-md-6">
                                <span class="requisition_header">Bill Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grn_list->bill_rec_date)); ?></span>
                            </div>
                            <?php endif; ?>

                            <div class="col-md-6">
                                <span class="requisition_header">Challan No. : </span><span class="requisition_text"><?php echo @$grn_list->challan_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Challan Date : </span><span class="requisition_text"><?php echo e(@$grn_list->challan_date); ?>

                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Date : </span><span class="requisition_text"><?php echo e(@$grn_list->invoice_date); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice No : </span><span class="requisition_text"><?php echo @$grn_list->invoice_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Value : </span><span class="requisition_text"><?php echo @$grn_list->invoice_value; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">PO. No. : </span><span class="requisition_text"><a target="_blank" href="<?php echo e(route('purchase-order-details')); ?>/<?php echo e(base64_encode($po_details->id)); ?>" style="color: blue;"><?php echo e($po_details->po_prefix); ?><?php echo e($po_details->id); ?></a>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total CGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_cgst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total SGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_sgst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total IGST Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_igst_amount; ?></span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Total Value : </span><span class="requisition_text"><span class="requisition_text"><?php echo @$grn_list->total_value; ?></span>
                                </span>
                            </div>
                    
                            <?php if(isset($grn_list->note)): ?>
                            <div class="col-md-12">
                                <span class="requisition_header">Note : </span><span class="requisition_text"><?php echo e(@$grn_list->note); ?></span>
                            </div>
                            <?php endif; ?>
                
                        </div>

                    </div>

                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>SL No.</th>
                            <th>Req. No.</th>
                            <th>Medicine Name</th>
                            <th>Catagory</th>
                            <th>Batch No.</th>
                            <th>Unit</th>
                            <th>Quantity</th>
                            <th>Discount</th>
                            <th>MRP</th>
                            <th>Purchase Rate</th>
                            <th>Sale Rate</th>
                            <th>CGST</th>
                            <th>CGST Value</th>
                            <th>SGST</th>
                            <th>SGST Value</th>
                            <th>IGST</th>
                            <th>IGST Value</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(isset($grn_item) && $grn_item != ''): ?>
                        <?php $__currentLoopData = $grn_item; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                        <tr>
                            <th scope="row"><?php echo e($loop->iteration); ?></th>
                            <td><?php echo e(@$item->req_id); ?></td>
                            <td><?php echo e(@$item->fetch_medicine_name->medicine_name); ?></td>
                            <td><?php echo e(@$item->fetch_medicine_catagory->medicine_catagory_name); ?></td>
                            <td><?php echo e(@$item->batch_no); ?></td>
                            <td><?php echo e(@$item->fetch_medicine_unit->medicine_unit_name); ?></td>
                            <td><?php echo e(@$item->qty); ?></td>
                            <td><?php echo e(@$item->discount); ?></td>
                            <td><?php echo e(@$item->mrp); ?></td>
                            <td><?php echo e(@$item->p_rate); ?></td>
                            <td><?php echo e(@$item->s_rate); ?></td>
                            <td><?php echo e(@$item->cgst); ?></td>
                            <td><?php echo e(@$item->cgst_value); ?></td>
                            <td><?php echo e(@$item->sgst); ?></td>
                            <td><?php echo e(@$item->sgst_value); ?></td>
                            <td><?php echo e(@$item->igst); ?></td>
                            <td><?php echo e(@$item->igst_value); ?></td>
                            <td><?php echo e(@$item->amount); ?></td>
                        </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                        <?php endif; ?>
                    </tbody>
                </table>
                <hr>

            </div><!-- bd -->
        </div>
    </div>
</div>











<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\xampp\htdocs\DITS-HMIS\resources\views/pharmacy/purchase/grn/grn-details.blade.php ENDPATH**/ ?>