
<?php $__env->startSection('content'); ?>
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">

        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Purchase Order List
                </div>

                <div class="col-md-8 text-right">
                    <div class="d-block">
                        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('add medicine purchase order')): ?>
                        <a href="<?php echo e(route('add-medicine-purchase-order')); ?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Create Purchase Order</a>
                        <?php endif; ?>
                    </div>
                </div>

            </div>
        </div>

        <?php echo $__env->make('message.notification', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('View Medicine Purchase Order')): ?>

        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table id="example" class="table table-borderless text-nowrap key-buttons">
                        <thead>
                            <tr>
                                <th scope="col">Sl No.</th>
                                <th scope="col">Purchase Order No.</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Store Room</th>
                                <th scope="col">Date</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(isset($po_list) && $po_list != ''): ?>
                            <?php $__currentLoopData = $po_list; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $po): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <th scope="row"><?php echo e($loop->iteration); ?></th>
                                <td><a href="<?php echo e(route('purchase-order-details')); ?>/<?php echo e(base64_encode($po->id)); ?>" style="color: blue;"><?php echo e($po->po_prefix); ?><?php echo e(@$po->id); ?></a></td>
                                <td><?php echo e($po->get_user_details->first_name); ?> <?php echo e($po->get_user_details->last_name); ?></td>
                                <td><?php echo e(@$po->get_store_details->name); ?></td>
                                <td><?= date('d-m-Y h:i', strtotime($po->po_date)); ?></td>
                                <td><?php echo @$po->get_wroking_status_details->status; ?></td>
                                <td>
                                    <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" style="">
                                            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('Print Medicine Purchase Order')): ?>
                                            <a class="dropdown-item" href="<?php echo e(route('po-print',['po_id'=> base64_encode($po->id)])); ?>"><i class="fa fa-print"></i> Print</a>
                                            <?php endif; ?>
                                            <a class="dropdown-item" href="<?php echo e(route('purchase-order-details')); ?>/<?php echo e(base64_encode($po->id)); ?>"><i class="fa fa-eye"></i> View</a>
                                            
                                            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete medicine purchase order')): ?>
                                            <a class="dropdown-item" href="<?php echo e(route('po-delete',['id'=>base64_encode($po->id)])); ?>"><i class="fa fa-trash"></i> Delete</a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </td>


                            </tr>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<script src="<?php echo e(asset('assets/js/jquery-3.6.0.min.js')); ?>"></script>
<script>
    $(document).ready(function() {
        $("#removeIcon").click(function(e) {
            e.preventDefault();
            $("#delete").submit();
        });
    });
</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\xampp\htdocs\DITS-HMIS-15-04-23\HMIS-HOSPITAL-MANAGEMENT\resources\views/pharmacy/purchase/purchase-order/medicine-purchase-order-listing.blade.php ENDPATH**/ ?>