
<?php $__env->startSection('content'); ?>

<?php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
?>



<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header">
            <div class="card-new">
            <div class="card-title">
                Purchase Order Details
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('Print Medicine Purchase Order')): ?>
                <a href="<?php echo e(route('po-print',['po_id'=> base64_encode($po_list->id)])); ?>" class="btn btn-primary btn-sm allbtndemo"><i class="fa fa-print"> Print</i></a>
                <?php endif; ?>
        
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('permission on po section')): ?>
                <a href="#" class="btn btn-primary btn-sm allbtndemoffff" data-target="#modaldemo1241" data-toggle="modal"><i class="fa fa-user"> Permission</i></a>
                <?php endif; ?>
            </div>
            </div>
        </div>
        <?php echo $__env->make('message.notification', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('view medicine requisition')): ?>
        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="requisition_header">Store Room : </span><span class="requisition_text"><?php echo e(@$po_list->get_store_details->name); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Purchase Order No. : </span><span class="requisition_text"><?php echo e($po_list->po_prefix); ?><?php echo e(@$po_list->id); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Purchase Order Date : </span><span class="requisition_text"><?= date('d-m-Y h:i', strtotime($po_list->po_date)); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Generated By : </span><span class="requisition_text"><?php echo e(@$po_list->get_user_details->first_name); ?><?php echo e(@$po_list->get_user_details->last_name); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Vendor : </span><span class="requisition_text"><?php echo e(@$po_list->get_vendor_details->vendor_name); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Note : </span><span class="requisition_text"><?php echo e(@$po_list->note); ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_text"><?php echo @$po_list->get_wroking_status_details->status; ?></span>
                            </div>
                        </div>

                        <div style="padding: 26px 0px 0px 0px;">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('save feedback')): ?>
                                        <?php if($po_list->status == 13 || $po_list->status == 19): ?>
                                        <a class="btn btn-primary btn-sm" data-target="#modaldemo3" data-toggle="modal" href="#"><i class="fa fa-envelope"></i> Upload Feedback</a>
                                        <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if(!empty($po_list->feedback)): ?>
                                        <a href="<?php echo e(asset('feedback/')); ?>/<?php echo e($po_list->feedback); ?>" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b> View Feedback</b></i></a>
                                        <?php endif; ?>
                                    </div>

                                    <?php if(!empty($po_list->feedback)): ?>
                                    <div class="col-md-6">
                                        <span data-toggle="tooltip-primary" data-placement="top" title="Upload Expected Delivary Date">
                                            <?php if($po_list->status > 11 && $po_list->status < 15 || $po_list->status == 19): ?>
                                                <a class="btn btn-primary btn-sm" data-target="#modaldemo12" data-toggle="modal" href="#"><i class="fa fa-calendar"></i></a></span>
                                        <?php endif; ?>
                                        <?php if(!empty($po_list->expected_delivery_date)): ?>
                                        <span class="requisition_header">Expected Delivary Date : </span><span class="requisition_text"><?= date('d-m-Y', strtotime($po_list->expected_delivery_date)); ?></span>
                                        <?php endif; ?>

                                    </div>
                                    <?php endif; ?>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Requisition Id</th>
                            <th>Medicine Name</th>
                            <th>Medicine Unit</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(isset($po_item) && $po_item != ''): ?>
                        <?php $__currentLoopData = $po_item; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                        <tr>
                            <th scope="row"><?php echo e($loop->iteration); ?></th>
                            <td><?php echo e(@$item->req_id); ?></td>
                            <td><?php echo e(@$item->fetch_medicine_name->medicine_name); ?>(<?php echo e(@$item->fetch_medicine_name->catagory_name->medicine_catagory_name); ?>)</td>
                            <td><?php echo e(@$item->fetch_medicine_unit->medicine_unit_name); ?></td>
                            <td><?php echo e(@$item->quantity); ?></td>
                        </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                        <?php endif; ?>
                    </tbody>
                </table>


            </div><!-- bd -->
        </div>
        <?php endif; ?>
    </div>
</div>

<div class="modal" id="modaldemo3">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Upload Feedback</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('feedback-save')); ?>" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="po_id" value="<?php echo e($po_list->id); ?>">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Feedback <span class="text-danger">*</span></label>
                        <input type="file" value="<?php echo e(@$po_list->feedback); ?>" required name="feedback_file">
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="modaldemo12">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Expected Delivery Date</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('expected-delivery-date')); ?>" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="po_id" value="<?php echo e($po_list->id); ?>">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Expected Delivery Date <span class="text-danger">*</span></label>
                        <input type="date" value="<?php echo e(@$po_list->expected_delivery_date); ?>" required name="expected_delivery_date" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="modaldemo1241">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h6 class="modal-title">Purchase Order</h6><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="POST" action="<?php echo e(route('po-status-change')); ?>" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="po_id" value="<?php echo e($po_list->id); ?>">
                <input type="hidden" name="vendor_id" value="<?php echo e($po_list->get_vendor_details->id); ?>">
                <div class="modal-body">
                    <div class="col-md-12">
                        <label class="form-label">Status <span class="text-danger">*</span></label>
                        <select class="form-control" name="status">
                            <option vlue="" disabled>Select One</option>
                            
                            <option value="17" <?php if ($po_list->status == 17) {
                                                    echo "selected";
                                                } ?>>Purchase Order Confirmed</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-indigo" type="submit"><i class="fa fa-paper-plane"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- ================================ vendor quatation details========================= -->

<!-- ================================ vendor quatation details========================= -->

<!--  -->








<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\xampp\htdocs\DITS-HMIS\resources\views/pharmacy/purchase/purchase-order/medicine-purchase-order-details.blade.php ENDPATH**/ ?>