<?php $__env->startSection('content'); ?>




    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Requisition List</div>
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create requisition')): ?>
                <div class="btn-list ggdtretew">
                    <a href="<?php echo e(route('create-requisition')); ?>" class="btn btn-primary"><i class="fa fa-plus"></i>  Create Requisition</a>
                </div>
                <?php endif; ?>
            </div>
            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('view requisition')): ?>

            <div class="card-body">
                <div class="">
                    <div class="table-responsive">
                        <table id="example" class="table table-borderless text-nowrap key-buttons">
                    <thead>
                        <tr>
                            <th scope="col">Sl No.</th>
                            <th scope="col">Requisition No.</th>
                            <th scope="col">Generated By</th>
                            <th scope="col">Workshop</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(isset($requisition_list) && $requisition_list != ''): ?>
                        <?php $__currentLoopData = $requisition_list; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $requisition): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <th scope="row"><?php echo e($loop->iteration); ?></th>
                                <td><a href="<?php echo e(url('requisition-details')); ?>/<?php echo e($requisition->req_no); ?>"><?php echo e($prefix->prefix); ?><?php echo e(@$requisition->req_no); ?></a></td>
                                <td><?php echo e($requisition->name); ?></td>
                                <td><?php echo e(@$requisition->workshop_name); ?></td>
                                <td><?= date('d-m-Y h:i',strtotime($requisition->date)); ?></td>
                                <td><?php echo @$requisition->status; ?></td>
                               
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                        <?php endif; ?>
                    </tbody>
                </table>
                <!-- End Table with stripped rows -->
            </div>
        </div>
    </div>
    <?php endif; ?>
 </div>
</div>

    <script src="<?php echo e(asset('assets/js/jquery-3.6.0.min.js')); ?>"></script>
    <script>
        $(document).ready(function() {
            $("#removeIcon").click(function(e) {
                e.preventDefault();
                $("#delete").submit();
            });
        });
    </script>
<?php $__env->stopSection(); ?>









<?php echo $__env->make('layouts.layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH E:\xampp\ame_inventory\resources\views/appPages/item/requisition/requisition-list.blade.php ENDPATH**/ ?>