@extends('layouts.layout')
@section('content')
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Billing
                </div>
                <div class="col-md-8 text-right">
                    <div class="d-block">
                        @can('add emg billing')
                        <a href="{{ route('add-emg-billing', ['id' => base64_encode($emg_id)]) }}" class="btn btn-primary btn-sm"><i class="fa fa-money-bill"></i> Add Billing </a>
                        @endcan
                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-building"></i> <i class="fa fa-caret-down"></i></a>
                        <div class="dropdown-menu dropdown-menu-right" style="">
                            @include('emg.include.menu')
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @if (session('success'))
        <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ session('success') }}</div>
        @endif
        @if (session()->has('error'))
        <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ session('error') }}</div>
        @endif

        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table id="example" class="table table-bordered text-nowrap key-buttons">
                        <thead>
                            <tr>
                                <th class="border-bottom-0">Bill No.</th>
                                <th class="border-bottom-0">Date</th>
                                <th class="border-bottom-0">Total Amount</th>
                                <th class="border-bottom-0">Generated By</th>
                                <th class="border-bottom-0">Billing Status</th>
                                <th class="border-bottom-0">Payment Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (@$emg_billing_details)
                            @foreach ($emg_billing_details as $value)
                            <tr>

                                <td><a class="text-info" href="{{ route('emg-bill-details', ['bill_id' => base64_encode($value->id)]) }}">{{ $value->bill_prefix }}{{ $value->id }}</a>
                                </td>
                                <td>{{ date('d-m-Y h:i A', strtotime($value->bill_date)) }}</td>
                                <td>{{ $value->total_amount }}</td>
                                <td>{{ $value->created_details->first_name }}
                                    {{ $value->created_details->last_name }}
                                </td>
                                <td><span class="badge badge-success">{{ $value->status }}</span></td>
                                <td><span class="badge badge-success">{{ $value->payment_status }}</span></td>
                                <td>
                                    <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" style="">

                                            <a class="dropdown-item" href="">
                                                <i class="fa fa-eye"></i> View
                                            </a>

                                            @can('edit emg billing')
                                            <a class="dropdown-item" href="{{route('edit_emg_bill',['bill_id'=>$value->id])}}">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                            @endcan
                                            @can('delete emg billing')
                                            <a class="dropdown-item" href="{{route('delete-emg-bill',['bill_id'=>$value->id])}}">
                                                <i class="fa fa-trash"></i> Delete
                                            </a>
                                            @endcan

                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    @endsection