<?php

return [
    'guardian_prefix' => ['C/O', 'H/O', 'W/O'],
    'blood_groups' => ['A+', 'B+', 'AB+', 'O-', 'O+', 'AB-', 'A-', 'B-'],
    'marital_status' => ['Single', 'Married', 'Widowed', 'Separated', 'Not Specified'],
    'gender' => ['male', 'female', 'others'],
    'prefix' => ['Mr.', 'Mrs.', 'Baby', 'Dr.', 'Miss', 'Devi', 'Mst.'],
    'weeks' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    'productType' => ['Blood Group', 'Component'],
    'patient_types' => ['General', 'Swasthya Sathi', 'TPA', 'Medical Student'],
    'opd_setup' => ['By-Department', 'By-Doctor'],
    'registration_type' => ['By-Department', 'By-Doctor'],
    'vehicle_type_name' => ['Owned', 'Contractual'],
    'payment_mode_name' => ['Cash', 'Cheque', 'Transfer to Bank Account', 'UPI', 'Other', 'Online'],
    'ans' => ['Yes', 'No'],
    'status' => ['Pending', 'Approved', 'Cancel'],
    'appointment_priority' => ['Normal', 'Urgent', 'Very Urgent', 'Low'],
    'visit_purpose' => ['Visit', 'Inquiry', 'Seminar'],
    'visit_to' => ['Staff', 'OPD Patient', 'Emg Patient', 'Ipd Patient'],
    'call_type' => ['Incoming', 'Outcoming'],
    'complain_type' => ['Food quality', 'Hospital services', 'Long Wait Times', 'Billing Discrepancies'],
    'complain_source' => ['Online Advertising', 'From visitors', 'Front Office'],
    'operation_status' => ['Pending', 'Approved'],
    'permission_type' => ['Parallal'],
    'charges_type' => ['General', 'Sastha-Swathi', 'ESI', 'Star Health', 'IOCL','Corporate'],
    'discharge_type' => ['Death', 'Refferal', 'Normal', 'LAMA', 'DORB', 'DMA'],
    'patient_from' => ['Opd', 'Emg'],
    'main_operation_status' => ['Pending', 'Complete', 'Cancel'],
    'payment_terms' => ['Advance','After Billing'],
];
