@extends('layouts.layout')
@section('content')
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header d-block">
                <div class="row">
                    <div class="col-md-4 card-title">
                        Pathology Test
                    </div>
                    <div class="col-md-8 text-right">
                        <div class="d-block">
                            <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false"><i class="fa fa-building"></i> <i class="fa fa-caret-down"></i></a>
                        <div class="dropdown-menu dropdown-menu-right" style="">
                            @include('OPD.include.menu')
                        </div>
                        
                        </div>
                    </div>
                </div>
            </div>
            @include('message.notification')
            <div class="card-body">
                <div class="">
                    <div class="table-responsive">
                        <table class="table table-bordered text-nowrap" id="example">
                            <thead>
                                <tr>
                                    <th class="border-bottom-0">Sl No.</th>
                                    <th class="border-bottom-0">Date</th>
                                    <th class="border-bottom-0">Test Name</th>
                                    <th class="border-bottom-0">Category</th>
                                    <th class="border-bottom-0">Generated By</th>
                                    <th class="border-bottom-0">Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (@$pathology_patient_test)
                                    @foreach ($pathology_patient_test as $value)
                                
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{ @date('d-m-Y h:i A', strtotime($value->date)) }}</td>
                                            <td>{{ @$value->test_details->test_name }}</td>
                                            <td>{{ @$value->test_details->test_name }}</td>
                                            <td>{{ @$value->generator_details->first_name }} {{ @$value->generator_details->last_name }}</td>
                                            <td>{!! @$value->test_status !!}</td>
                                            <td>
                                            <div class="card-options">
                                                <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown"
                                                    aria-haspopup="true" aria-expanded="false"> Action <i
                                                        class="fa fa-caret-down"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right" style="">

                                                    <a class="dropdown-item" href="{{ route('opd-bill-details', ['bill_id' => base64_encode($value->id)]) }}">
                                                        <i class="fa fa-eye"></i> View
                                                    </a>

                                                    <a class="dropdown-item" href="">
                                                        <i class="fa fa-print"></i> Print
                                                    </a>

                                                    @can('edit opd billing')
                                                        <a class="dropdown-item" href="{{route('edit-opd-bill',['bill_id'=>$value->id])}}">
                                                            <i class="fa fa-edit"></i> Edit
                                                        </a>
                                                    @endcan
                                                    @can('delete opd billing')
                                                        <a class="dropdown-item" href="{{route('delete-opd-bill',['bill_id'=>$value->id])}}">
                                                            <i class="fa fa-trash"></i> Delete
                                                        </a>
                                                    @endcan

                                                </div>
                                            </div>
                                        </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                        {{-- {!! $opd_billing_details->links() !!} --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection
