@extends('layouts.layout')
@section('content')

@php
$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
@endphp
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                GRN Details
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="requisition_header">Workshop : </span><span class="requisition_text">{{ @$grm_list->workshop_name }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN No. : </span><span class="requisition_text">{{ @$grm_list->grm_prefix }}{{ @$grm_list->grm_id }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">GRN Date : </span><span class="requisition_text"><?= date('d-m-Y h:i', strtotime(@$grm_list->grm_date)) ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Generated By : </span><span class="requisition_text">{{ @$grm_list->name }}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Materials Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grm_list->material_rec_date)); ?></span>
                            </div>
                            @if (@isset($grm_list->bill_rec_date))
                            <div class="col-md-6">
                                <span class="requisition_header">Bill Rec. Date : </span><span class="requisition_text"><?php echo date('d-m-Y h:i', strtotime(@$grm_list->bill_rec_date)); ?></span>
                            </div>
                            @endif

                            <div class="col-md-6">
                                <span class="requisition_header">Challan No. : </span><span class="requisition_text"><?php echo @$grm_list->challan_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Challan Date : </span><span class="requisition_text">{{@$grm_list->challan_date}}
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Date : </span><span class="requisition_text">{{@$grm_list->invoice_date}}</span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice No : </span><span class="requisition_text"><?php echo @$grm_list->invoice_no; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">Invoice Value : </span><span class="requisition_text"><?php echo @$grm_list->invoice_value; ?></span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">PO. No. : </span><span class="requisition_text"><a target="_blank" href="{{ route('purchase-order-details-inventory',['id' => base64_encode($po_details->id) ] )}}" style="color: blue;">{{$po_details->po_prefix}}{{$po_details->id}}</a>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="requisition_header">PO. Value : </span><span class="requisition_text"><?php echo @$grm_list->po_value; ?></span>
                            </div>
                            @isset($grm_list->note)
                            <div class="col-md-12">
                                <span class="requisition_header">Note : </span><span class="requisition_text">{{ @$grm_list->note }}</span>
                            </div>
                            @endisset
                            @if (isset($grm_list->challan_copy) && $grm_list->challan_copy != '' && $grm_list->challan_copy != null)
                            <div class="col-md-6">
                                <a href="{{ asset('Challan_copy/') }}/{{ @$grm_list->challan_copy }}" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b>
                                            View Challan</b></i></a>
                            </div>
                            @endif
                            @if (isset($grm_list->invoice_copy) && $grm_list->invoice_copy != '' && $grm_list->invoice_copy != null)
                            <div class="col-md-6">
                                <a href="{{ asset('invoice_copy/') }}/{{ @$grm_list->invoice_copy }}" target="_blank" style="color: blue;font-size: 15px;"><i class="fa fa-eye"><b>
                                            View Invoice</b></i></a>
                            </div>
                            @endif
                        </div>

                    </div>
                    <?php $qr_details = 'GRM No. - ' . @$grm_list->grm_prefix . '' . @$grm_list->grm_id . ' , GRM Date - ' . date('d-m-Y h:i', strtotime(@$grm_list->grm_date)) . ' , Generated By - ' . @$grm_list->name; ?>
                    <div class="col-md-4">
                        <div class="col-md-6">
                            {!! QrCode::size(100)->generate($qr_details) !!}
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>SL No.</th>
                            <th>Req. No.</th>
                            <th>Item Name</th>
                            <th>Brand</th>
                            <th>Manufacturer</th>
                            <th>Quantity</th>
                            <th>GST</th>
                            <th>Rate</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (isset($grm_item) && $grm_item != '')
                        @foreach ($grm_item as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ @$item->req_id }}</td>
                            <td>{{ @$item->item_name }}<br>({{ @$item->item_description }})</td>
                            <td>{{ @$item->item_brand_name }}</td>
                            <td>{{ @$item->manufacture_name }}</td>
                            <td>{{ @$item->quantity }} {{ @$item->units }}</td>
                            <td>{{ @$item->gst }}</td>
                            <td>{{ @$item->rate }}</td>
                            <td>{{ @$item->amount }}</td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>

            </div><!-- bd -->
        </div>
    </div>
</div>

@endsection