@extends('layouts.layout')
@section('content')
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Radiology Test
                </div>
                <div class="col-md-8 text-right">
                    <div class="d-block">
                         @can('add-radiology-test-to-a-patient')
                        <a href="{{ route('add-radiology-test-to-a-patient') }}" class="btn btn-primary btn-sm"><i class="fa fa-money-bill"></i> Add </a>
                        @endcan 

                        <!-- @can('radiology test')
                        <a href="{{ route('radiology-test-list') }}" class="btn btn-primary btn-sm"><i class="fa fa-vials"></i> Radiology Test </a>
                        @endcan -->

                        {{-- @can('radiology billing list')
                        <a href="{{ route('radiology-details') }}" class="btn btn-primary btn-sm"><i class="fa fa-rupee-sign"></i> Billing </a>
                        @endcan --}}


                        @can('radiology test master')
                        <a href="{{ route('radiology-test-list') }}" class="btn btn-primary btn-sm"><i class="fa fa-mortar-pestle"></i> Radiology Test </a>
                        @endcan

                    </div>
                </div>
            </div>
        </div>
        @include('message.notification')
        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table class="table table-bordered text-nowrap" id="example">
                        <thead>
                            <tr>
                                <th class="border-bottom-0">Sl No.</th>
                                <th class="border-bottom-0">Patient Details</th>
                                <th class="border-bottom-0">Date</th>
                                <th class="border-bottom-0">Test Name</th>
                                <th class="border-bottom-0">Case Id</th>
                                <th class="border-bottom-0">Section</th>
                                <th class="border-bottom-0">Generated By</th>
                                {{-- <th class="border-bottom-0">Billing Status</th> --}}
                                <th class="border-bottom-0">Status</th>
                                <th class="border-bottom-0">Report</th>
                                <th class="border-bottom-0">Print</th>
                                <!-- <th>Action</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            @if (@$radiology_patient_test)
                            @foreach ($radiology_patient_test as $value)
                            <?php
                            if ($value->section == 'OPD') {
                                $opd_details = DB::table('opd_details')->where('case_id', $value->case_id)->first();
                                $section_id = $opd_details->id;
                            }
                            if ($value->section == 'IPD') {
                                $ipd_details = DB::table('ipd_details')->where('case_id', $value->case_id)->first();
                                $section_id = $ipd_details->id;
                            }
                            if ($value->section == 'EMG') {
                                $emg_details = DB::table('emg_details')->where('case_id', $value->case_id)->first();
                                $section_id = $emg_details->id;
                            }
                            ?>
                            <tr>
                                <td>{{$loop->iteration}}</td>

                                <td>{{ @$value->all_patient_details->prefix }} {{ @$value->all_patient_details->first_name }} {{ @$value->all_patient_details->middle_name }} {{ @$value->all_patient_details->last_name }}({{ @$value->all_patient_details->id }})</td>

                                <td>{{ @date('d-m-Y h:i A', strtotime($value->date)) }}</td>

                                <td>{{ @$value->test_details->test_name }}</td>
                                <td>{{ @$value->case_id }}</td>
                                <td><a class="textlink" href="{{ route('opd-profile', ['id' => base64_encode($section_id)]) }}">{{ @$value->section }}({{@$section_id}})</a>
                                </td>
                                <td>{{ @$value->generator_details->first_name }} {{ @$value->generator_details->last_name }}</td>
                                {{-- <td> {!! $value->billing_status == '0' ? '<span class="badge badge-warning">Billing Not Done</span>':'<span class="badge badge-success">Billing Done</span>' !!}</td> --}}
                                {{-- <td>
                                    {!! @$value->test_status !!}
                                </td> --}}
                                <td>
                                    @if($value->test_status == '0')
                                    
                                    <span class="badge badge-warning" onclick="sample_collection({{ $value->id }})" >Sample Not Collected</span>
                                    @elseif($value->test_status == '1')
                                    <span class="badge badge-success" onclick="sample_collection({{ $value->id }})">Sample Collected</span>
                                    @elseif($value->test_status == '2')
                                    <span class="badge badge-success" onclick="sample_collection({{ $value->id }})">Sample Collection inconplete</span>
                                    @else
                                    <span class="badge badge-success" onclick="sample_collection({{ $value->id }})">Report Done</span>
                                    @endif
                                </td>
                                <td>
                                    @if($value->test_status == '1' || $value->test_status == '2' || $value->test_status == '3')
                                    @can('add radiology test result details')
                                    <a class="btn btn-primary btn-sm" href="{{ route('add-radiology-test-result-details', ['id' => base64_encode($value->id)]) }}">
                                        <i class="fa fa-eye"></i> Add Result
                                    </a>
                                    @endcan
                                    @endif
                                </td>
                                <td>
                                    @if($value->test_status == '3')
                                    @can('print radiology result')
                                    <a class="btn btn-primary btn-sm" href="{{ route('print-radiology-result', ['id' => base64_encode($value->id)]) }}">
                                        <i class="fa fa-print"></i> Print Report
                                    </a>
                                    @endcan
                                    @endif
                                </td>
                                {{-- <td>
                                    <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" style="">

                                            <a class="dropdown-item" href="{{ route('opd-bill-details', ['bill_id' => base64_encode($value->id)]) }}">
                                <i class="fa fa-eye"></i> View
                                </a>

                                @can('edit-radiology-test-to-a-patient')
                                <a class="dropdown-item" href="{{route('edit-radiology-test-patient',['id'=>base64_encode($value->id)])}}">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                                @endcan

                                @can('delete-radiology-test-to-a-patient')
                                <a class="dropdown-item" href="{{route('delete-radiology-test-patient',['id'=>base64_encode($value->id)])}}">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                                @endcan

                </div>
            </div>
            </td> --}}
            </tr>
            @endforeach
            @endif
            </tbody>
            </table>
            {{-- {!! $opd_billing_details->links() !!} --}}
        </div>
    </div>
</div>
</div>
</div>
<div class="modal" id="modaldemo2">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Sample Collection</h6><button aria-label="Close" class="close"
                    data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form action="{{ route('change-sample-status-radiology') }}" method="post">
                @csrf
                <input name="id" type="hidden" id="p_id" />
                <div class="modal-body">
                    <div class="col-md-12">
                        <div class="row">
                            <select name="sample_status" class="form-control select2-show-search">
                                <option value="0">Sample Not Collected</option>
                                <option value="1">Sample Collected</option>
                                <option value="2">Sample Collection incomplete</option>
                                <option value="3">Report Done</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button class="btn btn-primary text-right" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function sample_collection(p_id)
    {
            $('#p_id').val(p_id);
            $('#modaldemo2').modal('show');
    }
</script>
@endsection