@extends('layouts.layout')
@section('content')
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">
        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Patient's Test 
                </div>
                <div class="col-md-8 text-right">
                    <div class="d-block">
                        @can('add-pathology-test-to-a-patient')
                        <a href="{{ route('add-pathology-test-to-a-patient') }}" class="btn btn-primary btn-sm"><i class="fa fa-money-bill"></i> Add </a>
                        @endcan
                        {{-- @can('pathology billing list')
                        <a href="{{ route('pathology-details') }}" class="btn btn-primary btn-sm"><i class="fa fa-rupee-sign"></i> Billing </a>
                        @endcan --}}
                      
                        @can('pathology test')
                        <a href="{{ route('pathology-test-list') }}" class="btn btn-primary btn-sm"><i class="fa fa-vials"></i> Pathology Test </a>
                        @endcan
                       

                    </div>
                </div>
            </div>
        </div>
        @include('message.notification')
        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table class="table table-bordered text-nowrap" id="example">
                        <thead>
                            <tr>
                                <th class="border-bottom-0">Sl No.</th>
                                <th class="border-bottom-0">Patient Details</th>
                                <th class="border-bottom-0">Date</th>
                                <th class="border-bottom-0">Test Name</th>
                                <th class="border-bottom-0">Case Id</th>
                                <th class="border-bottom-0">Section</th>
                                <th class="border-bottom-0">Generated By</th>
                                {{-- <th class="border-bottom-0">Billing Status</th> --}}
                                <th class="border-bottom-0">Status</th>
                                <th class="border-bottom-0">Report</th>
                                <th class="border-bottom-0">Print</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (@$pathology_patient_test)
                            @foreach ($pathology_patient_test as $value)
                            <?php
                            if ($value->section == 'OPD') {
                                $opd_details = DB::table('opd_details')->where('case_id', $value->case_id)->first();
                                $section_id = $opd_details->id;
                            }
                            if ($value->section == 'IPD') {
                                $ipd_details = DB::table('ipd_details')->where('case_id', $value->case_id)->first();
                                $section_id = $ipd_details->id;
                            }
                            if ($value->section == 'EMG') {
                                $emg_details = DB::table('emg_details')->where('case_id', $value->case_id)->first();
                                $section_id = $emg_details->id;
                            }
                            ?>
                            <tr>
                                <td>{{$loop->iteration}}</td>

                                <td>{{ @$value->all_patient_details->prefix }} {{ @$value->all_patient_details->first_name }} {{ @$value->all_patient_details->middle_name }} {{ @$value->all_patient_details->last_name }}({{ @$value->all_patient_details->id }})</td>

                                <td>{{ @date('d-m-Y h:i A', strtotime($value->date)) }}</td>

                                <td>{{ @$value->test_details->test_name }}</td>
                                <td>{{ @$value->case_id }}</td>
                                <td>
                                    
                                    @if ($value->section == 'OPD') 
                                    <a class="textlink" href="{{ route('opd-profile', ['id' => base64_encode($section_id)]) }}">{{ @$value->section }}({{@$section_id}})</a>
                                    
                                    @elseif ($value->section == 'IPD') 
                                    <a class="textlink" href="{{ route('ipd-profile', ['id' => base64_encode($section_id)]) }}">{{ @$value->section }}({{@$section_id}})</a>
                                    
                                    @else
                                    <a class="textlink" href="{{ route('emg-patient-profile', ['id' => base64_encode($section_id)]) }}">{{ @$value->section }}({{@$section_id}})</a>
                                    @endif

                                </td>
                                <td>{{ @$value->generator_details->first_name }} {{ @$value->generator_details->last_name }}</td>

                                {{-- <td>
                                    @if($value->billing_status == '0')
                                    <span class="badge badge-warning">Billing Not Done</span>
                                    @elseif ($value->billing_status == '1')
                                    <span class="badge badge-warning">Billing Done</span>
                                    @else
                                    <span class="badge badge-warning">Charge Added</span>
                                    @endif
                                </td>  --}}
                                <td>
                                    @if($value->test_status == '0')
                                    
                                    <span class="badge badge-warning" onclick="sample_collection({{ $value->id }})" >Sample Not Collected</span>
                                    @else
                                    <span class="badge badge-success">Sample Collected</span>
                                    @endif
                                </td>
                                <td>
                                    @can('add pathology test result details')
                                          <a class="btn btn-primary btn-sm" href="{{ route('add-pathology-test-result-details', ['id' => base64_encode($value->id)]) }}">
                                        <i class="fa fa-eye"></i> Add Result
                                    </a>
                                    @endcan
                                  
                                    {{-- <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" style="">

                                            <a class="dropdown-item" href="{{ route('opd-bill-details', ['bill_id' => base64_encode($value->id)]) }}">
                                                <i class="fa fa-eye"></i> View
                                            </a> --}}

                                            {{-- @can('edit-pathology-test-to-a-patient')
                                            <a class="dropdown-item" href="{{route('edit-pathology-test-patient',['id'=>base64_encode($value->id)])}}">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                            @endcan

                                            @can('delete-pathology-test-to-a-patient')
                                            <a class="dropdown-item" href="{{route('delete-pathology-test-patient',['id'=>base64_encode($value->id)])}}">
                                                <i class="fa fa-trash"></i> Delete
                                            </a>
                                            @endcan --}}

                                        {{-- </div>
                                    </div> --}}
                                </td>
                                <td>
                                    @can('print pathology result')
                                    <a class="btn btn-primary btn-sm" href="{{ route('print-pathology-result', ['id' => base64_encode($value->id)]) }}">
                                  <i class="fa fa-print"></i> Print Report
                              </a>
                              @endcan
                                </td>
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                    {{-- {!! $opd_billing_details->links() !!} --}}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="modaldemo2">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Sample Collection</h6><button aria-label="Close" class="close"
                    data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
            </div>
            <form action="{{ route('change-sample-status') }}" method="post">
                @csrf
                <input name="id" type="hidden" id="p_id" />
                <div class="modal-body">
                    <div class="col-md-12">
                        <div class="row">
                            <select name="sample_status" class="form-control select2-show-search">
                                <option value="0">Sample Not Collected</option>
                                <option value="1">Sample Collected</option>
                                <option value="2">Sample Collection incomplete</option>
                                <option value="2">Report Done</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button class="btn btn-primary text-right" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function sample_collection(p_id)
    {
            $('#p_id').val(p_id);
            $('#modaldemo2').modal('show');
    }
</script>
@endsection