@extends('layouts.layout')
@section('content')


<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">

        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Requisition List
                </div>

                <div class="col-md-8 text-right">
                    <div class="d-block">
                        @can('create Purchase Order Inventory')

                        <a href="{{route('create-po-inventory')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Purchase Order</a>

                        @endcan
                    </div>
                </div>
            </div>
        </div>


        <!-- ================================= Message ======================================== -->
        @if (session('success'))
        <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{session('success')}}</div>
        @endif
        @if (session()->has('error'))
        <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{session('error')}}</div>
        @endif
        <!-- ================================= Message ======================================== -->
        @can('view requisition')
        <div class="card-body">
            <div class="">
                <div class="table-responsive">
                    <table id="example" class="table table-borderless text-nowrap key-buttons">
                        <thead>
                            <tr>
                                <th scope="col">Sl No.</th>
                                <th scope="col">Purchase Order No.</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Workshop</th>
                                <th scope="col">Date</th>
                                <th scope="col">Payment Terms</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($po_list as $item)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td><a href="{{ route('purchase-order-details-inventory',['id'=> base64_encode($item->id)]) }}" style="color: blue;">{{$item->po_prefix }}{{ @$item->id }}</a></td>
                                <td>{{ $item->user_details->first_name}} {{ $item->user_details->last_name}}</td>
                                <td>{{ @$item->store_room->item_store_room}} </td>
                                <td>{{ @$item->po_date}} </td>
                                <td><span class="badge badge-primary">{{ @$item->payment_terms }}</span></td>
                                <td>{!!@$item->working_status->status!!}</td>
                                <td>
                                    <div class="card-options">
                                        <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <i class="fa fa-caret-down"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">

                                            @can('view medicine requisition')
                                            <a class="dropdown-item" href="{{ route('purchase-order-details-inventory',['id'=> base64_encode($item->id)]) }}" ><i class="fa fa-eye"></i> View</a>
                                            @endcan

                                            @can('edit medicine requisition')
                                            <a class="dropdown-item" href="{{ route('po-print-inven',['po_id'=> base64_encode($item->id)]) }}"><i class="fa fa-edit"></i> Print</a>
                                            @endcan

                                            @can('delete medicine requisition')
                                            <a class="dropdown-item" href="{{ route('po-delete-inven',['po_id'=> base64_encode($item->id)]) }}"><i class="fa fa-trash"></i> Delete</a>
                                            @endcan
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->
                </div>
            </div>
        </div>
        @endcan
    </div>
</div>
<script src="{{ asset('assets/js/jquery-3.6.0.min.js') }}"></script>

@endsection