@extends('layouts.layout')
@section('content')
<div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
    <div class="card">

        <div class="card-header d-block">
            <div class="row">
                <div class="col-md-4 card-title">
                    Item Issue
                </div>

                <div class="col-md-8 text-right">
                    <div class="d-block">
                        @can('Create Item Issue Inventory')
                        <a href="{{ route('add-item-issue-inventory') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Issue Item</a>
                        @endcan

                    </div>
                </div>
            </div>

        </div>
        @include('message.notification')
        <div class="card-body ">
            <div class="row no-gutters">
                <div class="col-md-12 mt-2">
                    <div class="table-responsive">
                        <table class="table table-bordered text-nowrap" id="example">
                            <thead>
                                <tr>
                                    <th class="border-bottom-0">Sl. No</th>
                                    <th class="border-bottom-0">ISSUE SLIP NO</th>
                                    <th class="border-bottom-0">ISSUE FROM</th>
                                    <th class="border-bottom-0">ISSUE TO</th>
                                    <th class="border-bottom-0">GENERATED BY</th>
                                    <th class="border-bottom-0">ISSUED BY</th>
                                    <th class="border-bottom-0">ISSUE DATE</th>
                                    <th class="border-bottom-0">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($item_issue_list as $item)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td><a href="{{ route('item-issue-details-inventory',['issue_id' => $item->id ]) }}" style="color: blue;">{{$item->issue_prefix }}{{ @$item->id }}</a></td>
                                    <td>{{ $item->store_room_details->item_store_room}}</td>
                                    <td>{{ $item->issue_to_details->first_name}} {{ $item->issue_to_details->last_name}}</td>
                                    <td>{{ $item->generated_by_details->first_name}} {{ $item->generated_by_details->last_name}}</td>
                                    <td>{{ $item->issue_by_details->first_name}} {{ $item->issue_by_details->last_name}}</td>
                                    <td>{{ @$item->issue_date}} </td>
                                    <td>
                                        <div class="card-options">
                                            <a href="#" class="btn btn-primary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <i class="fa fa-caret-down"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">

                                                @can('view item issue inventory')
                                                <a class="dropdown-item" href="{{ route('item-issue-details-inventory',['issue_id' => $item->id ]) }}"><i class="fa fa-eye"></i> View</a>
                                                @endcan

                                                @can('edit item issue inventory')
                                                <a class="dropdown-item" href="{{ route('edit-item-issue-inventory',['issue_id'=> base64_encode($item->id)]) }}"><i class="fa fa-edit"></i> Edit</a>
                                                @endcan

                                                @can('delete item issue inventory')
                                                <a class="dropdown-item" href="{{ route('delete-item-issue-inventory',['issue_id'=> base64_encode($item->id)]) }}"><i class="fa fa-trash"></i> Delete</a>
                                                @endcan
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection